name = "LessUnits"
uuid = "05e0e9bd-d7a3-4127-a531-85e488807e56"
version = "0.0.1"
authors = ["Vasilii Vadimov"]

[deps]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Unitful = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
